Symfony/src/Entity/Publication.php
<?php

namespace App\Entity;

use App\Repository\PublicationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PublicationRepository::class)
 */
class Publication
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @Groups("post:read")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank (message = "Le nom ne doit pas etre vide")
     * @ORM\Column(type="string", length=255, nullable=true)
     *  @Groups("post:read")
     */
    private $nom;

    /**
     * @Assert\NotBlank (message ="la description ne doit pas etre vide")
     * @Assert\Length(min=10, minMessage="La description doit au moins avoir 10 caracteres")
     * @ORM\Column(type="string", length=255)
     *  @Groups("post:read")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     *
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     *  @Groups("post:read")
     */
    private $adresse;

    /**
     * @ORM\Column(type="date")
     *
     */
    private $datecreation = 'CURRENT_TIMESTAMP';

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="idPublication")
     *
     */
    private $commentaires;

    function __construct() {
        $this->datecreation=new \DateTime();
        $this->commentaires = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getDatecreation(): ?\DateTimeInterface
    {
        return $this->datecreation;
    }

    public function setDatecreation(\DateTimeInterface $datecreation): self
    {
        $this->datecreation = $datecreation;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setIdPublication($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getIdPublication() === $this) {
                $commentaire->setIdPublication(null);
            }
        }

        return $this;
    }
}

Symfony/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @groups("post:read")
     */
    private $id_user;

    /**
     * @Assert\NotBlank(message = "Veuillez ecrire l'email.")
     *
     * @ORM\Column(type="string", length=180, unique=true)
     *  @groups("post:read")
     */
    private $email;

    /**
     * @ORM\Column(type="string")
     *  @groups("post:read")
     * 
     */
    private $roles = "ROLE_USER";

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     *  @groups("post:read")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $Nom;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="string", length=255)
     */
    private $Adress;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="string", length=255)
     */
    private $Date_nais;

    public function getId_user(): ?int
    {
        return $this->id_user;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): string
    {
        return (string) $this->roles;
    }

    public function setRoles(string $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }


    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->Adress;
    }

    public function setAdress(string $Adress): self
    {
        $this->Adress = $Adress;

        return $this;
    }

    public function getDateNais(): ?string
    {
        return $this->Date_nais;
    }

    public function setDateNais(string $Date_nais): self
    {
        $this->Date_nais = $Date_nais;

        return $this;
    }

    public function __toString()
    {
        return $this->email;
    }
}

Symfony/src/Form/PublicationType.php
<?php

namespace App\Form;

use App\Entity\Publication;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class PublicationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('description')
            ->add('image',FileType::Class,[
                'mapped'=>false,
                'required'=>false,
            ])
            ->add('adresse')

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Publication::class,
        ]);
    }
}

Symfony/src/Controller/PublicationController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Entity\Publication;
use App\Form\CommentaireType;
use App\Form\PublicationType;
use App\Repository\PublicationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Gedmo\Sluggable\Util\Urlizer;
use mofodojodino\ProfanityFilter\Check;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

/**
 * @Route("/publication")
 */
class PublicationController extends AbstractController
{

    /**
     *
    @Route("/", name="app_publication_index", methods={"GET"})
     */
    public function index(PublicationRepository $publicationRepository): Response
    {
        return $this->render('publication/index.html.twig', [
            'publications' => $publicationRepository->findAll(),
        ]);
    }
    /**
     * @Route("/front", name="app_publicationF_index", methods={"GET"})
     */
    public function indexF(EntityManagerInterface $entityManager ,Request $request, PaginatorInterface $paginator): Response
    {
        $publications = $paginator->paginate(
            $publications = $entityManager
                ->getRepository(Publication::class)
                ->findAll(),
            $request->query->getInt('page', 1),
            3
        );
        return $this->render('publication/front-pub.html.twig',[
            'publications' => $publications,
        ]);
    }

    /**
     * @Route("/new", name="app_publication_new", methods={"GET", "POST"})
     */
    public function new(Request $request, PublicationRepository $publicationRepository): Response
    {
        $publication = new Publication();
        $form = $this->createForm(PublicationType::class, $publication);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /**
             * @var UploadedFile $uploadedFile
             */
            $uploadedFile = $form['image']->getData();
            $lastFile = $publication->getImage();
            if ($form['image']->getData() == null){

                $publication->setImage($lastFile);
            }
            if ($uploadedFile) {
                $destination = $this->getParameter('kernel.project_dir') . '/public/image';
                $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $newFilename = Urlizer::urlize($originalFilename) . '-' . uniqid() . '.' . $uploadedFile->guessClientExtension();
                $uploadedFile->move(
                    $destination,
                    $newFilename
                );
                $publication->setImage($newFilename);
            }
            $publicationRepository->add($publication);
            return $this->redirectToRoute('app_publication_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('publication/new.html.twig', [
            'publication' => $publication,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_publication_show", methods={"GET"})
     */
    public function show(Publication $publication): Response
    {
        return $this->render('publication/show.html.twig', [
            'publication' => $publication,
        ]);
    }

    /**
     * @Route("/f/{id}", name="app_publication_front_show")
     */
    public function showfront(Publication $publication, EntityManagerInterface $entityManager,$id, Request $request): Response
    { $em=$this->getDoctrine()->getManager();
        $commentaires = $entityManager
            ->getRepository(Commentaire::class)
            ->findBy(['idPublication'=>$id]);
        $query=$entityManager
            ->createQuery("select count(s) from App\Entity\Commentaire s where s.idPublication=:id  ")
            ->setParameter('id',$id);
        $number=$query->getSingleScalarResult();
        $dql = "SELECT AVG(e.note) AS rating FROM App\Entity\Commentaire e "."WHERE e.idPublication = :id  ";
        $rating = $em->createQuery($dql)
            ->setParameter('id', $id)
            ->getSingleScalarResult();


        $check = new Check( '../config/profanities.php');
        $commentaires2 = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaires2);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $verifier = $form['comment']->getData();
            $hasProfanity = $check->hasProfanity($verifier);
            if ($hasProfanity == false) {
                $commentaires2->setIdPublication($publication);
                $entityManager->persist($commentaires2);
                $entityManager->flush();
                $good="good";
                return $this->redirectToRoute('app_publication_front_show',[
                    "id"=>$id,"good"=>$good
                ]);
            }else {
                $bad="bad";
                return $this->redirectToRoute('app_publication_front_show',[
                    "id"=>$id,"bad"=>$bad
                ]);
            }
        }
        return $this->render('publication/show_front.html.twig', [
            'publication' => $publication,'commentaires'=>$commentaires,'commentairesform'=>$commentaires2,
            'form' => $form->createView(),'idpub'=>$id,'number'=>$number,'rating'=>$rating,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_publication_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Publication $publication, PublicationRepository $publicationRepository): Response
    {
        $form = $this->createForm(PublicationType::class, $publication);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $publicationRepository->add($publication);
            return $this->redirectToRoute('app_publication_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('publication/edit.html.twig', [
            'publication' => $publication,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_publication_delete", methods={"POST"})
     */
    public function delete(Request $request, Publication $publication, PublicationRepository $publicationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$publication->getId(), $request->request->get('_token'))) {
            $publicationRepository->remove($publication);
        }

        return $this->redirectToRoute('app_publication_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/DownloadProduitsData", name="DownloadProduitsData")
     */
    public function DownloadProduitsData(PublicationRepository $repository)
    {
        $Publication=$repository->findAll();

        // On définit les options du PDF
        $pdfOptions = new Options();
        // Police par défaut
        $pdfOptions->set('defaultFont', 'Arial');
        $pdfOptions->setIsRemoteEnabled(true);

        // On instancie Dompdf
        $dompdf = new Dompdf($pdfOptions);
        $context = stream_context_create([
            'ssl' => [
                'verify_peer' => FALSE,
                'verify_peer_name' => FALSE,
                'allow_self_signed' => TRUE
            ]
        ]);
        $dompdf->setHttpContext($context);

        // On génère le html
        $html = $this->renderView('publication/download.html.twig',
            ['Publication'=>$Publication ]);


        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        // On génère un nom de fichier
        $fichier = 'Tableau des publication.pdf';

        // On envoie le PDF au navigateur
        $dompdf->stream($fichier, [
            'Attachment' => true
        ]);

        return new Response();

    }


}

Symfony/templates/publication/_delete_form.html.twig
<form method="post" action="{{ path('app_publication_delete', {'id': publication.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ publication.id) }}">
    <button class="btn">Delete</button>
</form>

Symfony/templates/publication/_form.html.twig
<style>li{
        color:red;
    }</style>
{{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Symfony/templates/publication/download.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Tableau des publication</title>
</head>
<body >
<h1 style="text-align: center; color: red">Trenna</h1>
<h2 style="text-align: center">Tableau des evenement</h2>

<table border="1">
    <thead>
    <tr>

        <th>Nom</th>
        <th>description</th>
        <th>adresse</th>


    </tr>
    </thead>
    <tbody>
    {% for c in Publication %}
        <tr>
            <td>{{ c.nom }}</td>
            <td>{{ c.description }}</td>
            <td>{{ c.adresse }}</td>

        </tr>
    {% endfor %}
    </tbody>
</table>


</body>
</html>

Symfony/templates/publication/edit.html.twig
{% extends 'index.html.twig' %}

{% block title %}Edit Publication{% endblock %}

{% block body %}
    <h1>Edit Publication</h1>

    {{ include('publication/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_publication_index') }}">back to list</a>

    {{ include('publication/_delete_form.html.twig') }}
{% endblock %}

Symfony/templates/publication/front-pub.html.twig
{% extends 'basef.html.twig' %}
{% block body %}

    <section class="section" id="trainers">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="section-heading">
                        <h2><em>Publications</em></h2>
                        <img src="{{ asset('assets/images/line-dec.png') }}" alt="">
                        <p>Publier, liker et interagisser avec nos autres membres.</p>
                    </div>
                </div>
            </div>
            {% for pub in publications %}

            <div class="row">
                <div class="col-lg-4">
                    <div class="trainer-item">
                        <div class="image-thumb">
                            <img img  src="{{  asset ("image/#{pub.image}") }}" alt="">
                        </div>
                        <div class="down-content">
                            <span>{{ pub.adresse }}</span>
                            <h4>{{ pub.nom }}</h4>
                            <p>{{ pub.description }}</p>

                            <a href="{{ path('app_publication_front_show', {'id': pub.id}) }}" class="read-more">Voir Plus <i class="fa fa-angle-right"></i></a>

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
        <div class="pagination">
            {{ knp_pagination_render(publications) }}
        </div>
    </section>
    <!-- ***** Testimonials Ends ***** -->
{% endblock %}

Symfony/templates/publication/index.html.twig
{% extends 'index.html.twig' %}

{% block title %}Publication index{% endblock %}

{% block body %}
    <h1>Publication index</h1>
    <td>
        <p style="100px" > <input  id="myInput"  type="text" placeholder="search">
            <img src="https://img.icons8.com/nolan/344/google-web-search.png" style="width:50px;height:50px;"/></p>
    </td>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Description</th>
                <th>Image</th>
                <th>Adresse</th>
                <th>Datecreation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        <tbody>
        <tbody id="myTable">
        {% for publication in publications %}
            <tr>
                <td>{{ publication.id }}</td>
                <td>{{ publication.nom }}</td>
                <td>{{ publication.description }}</td>
                <td>{{ publication.image }}</td>
                <td>{{ publication.adresse }}</td>

                <td>
                    <a href="{{ path('app_publication_show', {'id': publication.id}) }}">show</a>
                    <a href="{{ path('app_publication_edit', {'id': publication.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
        <tbody id="search">
        </tbody>
    </table>
    <a href="{{ path('DownloadProduitsData') }}" class="btn btn-dark waves-effect waves-light">Download PDF</a>

    <a href="{{ path('app_publication_new') }}">Create new</a>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
{% endblock %}

Symfony/templates/publication/new.html.twig
{% extends 'index.html.twig' %}

{% block title %}New Publication{% endblock %}

{% block body %}
    <h1>Create new Publication</h1>

    {{ include('publication/_form.html.twig') }}

    <a href="{{ path('app_publication_index') }}">back to list</a>
{% endblock %}

Symfony/templates/publication/show.html.twig
{% extends 'index.html.twig' %}

{% block title %}Publication{% endblock %}

{% block body %}
    <h1>Publication</h1>


    <table class="table">
        <tbody>

            <tr>
                <th>Id</th>
                <td>{{ publication.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ publication.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ publication.description }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ publication.image }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ publication.adresse }}</td>
            </tr>
            <tr>
                <th>Datecreation</th>
                <td>{{ publication.datecreation ? publication.datecreation|date('Y-m-d') : '' }}</td>
            </tr>

        </tbody>
    </table>

    <a href="{{ path('app_publication_index') }}">back to list</a>

    <a href="{{ path('app_publication_edit', {'id': publication.id}) }}">edit</a>

    {{ include('publication/_delete_form.html.twig') }}

{% endblock %}

Symfony/templates/publication/show_front.html.twig
{% extends 'basef.html.twig' %}
{% block body %}
    <style> li{
            color:red;
        }
    </style>
    <div id="titlebar" class="gradient">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>Bienvenue !! </h2>
                    <nav id="breadcrumbs">
                        <ul>

                            <li><a href="{{ path('app_publicationF_index') }}"> Retour</a></li>
                            <li>La publication en details</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="blog-page">
            <div class="row">
                <div class="col-lg-8 col-md-8">
                    <div class="utf_blog_post utf_single_post">
                        <a  class="utf_post_img"> <img  src="{{  asset ("image/#{publication.image}") }}" alt=""> </a>
                        <div class="utf_post_content">
                            <h3>{{ publication.nom }}</h3>
                            <ul class="utf_post_text_meta">
                                <span class="date"><i class="fa fa-clock-o"></i> {{ publication.datecreation ? publication.datecreation|date('Y-m-d') : '' }}</span>


                                <li><a href="#">{{ number }} comments</a></li>
                            </ul>
                            <div class="utf_post_quote"> <span class="icon"></span>
                                <blockquote> {{ publication.adresse }}</blockquote>
                            </div>
                            <p>{{ publication.description }}</p>

                            <div class="utf_box_widget opening-hours review-avg-wrapper margin-top-35 margin-bottom-70">
                                <h3><i class="sl sl-icon-star"></i>  Rating Average</h3>

                                    <div class="rating-avg-wrapper text-theme clearfix">
                                        <div class="rating-avg">{{ rating |number_format(1)}}</div>
                                        <div class="rating-after">
                                            <div class="rating-mode">/5 Average</div>

                                        </div>


                                </div>
                            </div>

                        </div>
                    </div>
               {#   <a href="{{ path('app_publication_edit', {'id': publication.id}) }}" class="button border">Modifier</a>
                    <a href="{{ path('app_publication_front_delete', {'id': publication.id}) }}" onclick="return confirm('Are you sure you want to delete this item?');" class="button border">Supprimer</a>  #}

                    <div class="clearfix"></div>


                    <section class="comments">
                        <h4 class="headline_part margin-top-20 margin-bottom-35"> <i class="fa fa-comments" ></i>Comments <span class="comments-amount">({{ number }})</span></h4>
                        <ul>
                            {% if app.request.query.get("bad") == "bad" %}
                                <h4 class="text-danger mt-4 mb-4"> Erreur ajout commentaire !, Bad words</h4>
                            {% endif %}
                            {% if app.request.query.get("good") == "good" %}
                                <h4 class="text-success mt-4 mb-4"> commentaire ajouté avec succes</h4>
                            {% endif %}
                            {% for c in commentaires %}
                                <li>
                                 {#     <div class="avatar"><img src="{{ asset("Front-office/images/#{c.idGuest.imageProfile}") }}" alt=""></div> #}
                                    <div class="utf_comment_content">
                                        <div class="utf_arrow_comment"></div>
                                     {#   <div style="font-weight: bold;color:#282b42" >{{ c.idguest.nom }} {{ c.idguest.prenom }}</div>  #}
                                        {#    <div class="utf_star_rating_section" data-rating="4.5"><span class="star"></span><span class="star"></span><span class="star"></span><span class="star"></span><span class="star half"></span></div> #}
                                        {% if c.note==1  %}
                                            <i style="color:gold " class ='fa fa-star '></i> <i class ='fa fa-star '  ></i><i class ='fa fa-star '  ></i><i class ='fa fa-star '  ></i><i class ='fa fa-star '  ></i>
                                        {% elseif c.note==2 %}
                                            <i style="color: gold" class ='fa fa-star '  ></i> <i style="color: gold" class ='fa fa-star '></i><i class ='fa fa-star '  ></i><i class ='fa fa-star '  ></i><i class ='fa fa-star '  ></i>
                                        {% elseif c.note==3 %}
                                            <i style="color: gold" class ='fa fa-star '  ></i> <i style="color: gold" class ='fa fa-star '  ></i><i style="color: gold" class ='fa fa-star '  ></i><i class ='fa fa-star '  ></i><i class ='fa fa-star '  ></i>
                                        {% elseif c.note==4 %}
                                            <i style="color: gold" class ='fa fa-star '  ></i><i style="color: gold" class ='fa fa-star '  ></i> <i style="color: gold" class ='fa fa-star '  ></i><i style="color: gold" class ='fa fa-star '  ></i><i class ='fa fa-star '  ></i>
                                        {% else %}
                                            <i style="color: gold" class ='fa fa-star '  ></i> <i style="color: gold" class ='fa fa-star '  ></i><i style="color: gold" class ='fa fa-star '  ></i><i style="color: gold" class ='fa fa-star '  ></i><i style="color: gold" class ='fa fa-star '  ></i>
                                        {% endif %}

                                       {# <div class="utf_by_comment" style="font-family: Dialog ; color: #4f5050" >{{ c.nom }}<span class="date"><i class="fa fa-clock-o"></i> {{ publication.datecreation ? publication.datecreation|date('Y-m-d') : '' }}</span>  <a href="{{ path('app_commentaire_front_delete', {'id':c.id ,'idpub':idpub}) }}" onclick="return confirm('Are you sure you want to delete this item?');" class="reply">Supprimer <i class="fa fa-times"></i></a>   </div>   #}
                                        <p>{{ c.comment }}</p>

                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </section>
                    <div class="clearfix"></div>

                    <div id="utf_add_review" class="utf_add_review-box">

                        <h3 class="utf_listing_headline_part margin-bottom-35"   > <i class="fa fa-pencil-square-o"></i> Ajouter votre commentaire</h3>

                        {{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
                        <fieldset>
                            <div class="row">
                                <div class="col-md-4">
                                    {{ form_row(form.nom) }}
                                </div>
                                <div class="col-md-4">
                                    {{ form_row(form.note) }}
                                </div>
                            </div>
                            <div>
                                {{ form_row(form.comment) }}
                            </div>
                        </fieldset>
                        <button class="button">Poster</button>
                        <div class="clearfix"></div>
                        {{ form_end(form) }}
                    </div>
                </div>


            </div>
        </div>
    </div>

{% endblock %}